In [3]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv('/content/train_loan_preprocess.csv')
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [6]:
df.isna().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [7]:
df.fillna(method='ffill',inplace=True)
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [8]:
df.fillna(method='bfill',inplace=True)
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,128.0,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [9]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,128.0,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             614 non-null    object
 2   Married            614 non-null    object
 3   Dependents         614 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      614 non-null    object
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         614 non-null    float64
 9   Loan_Amount_Term   614 non-null    float64
 10  Credit_History     614 non-null    float64
 11  Property_Area      614 non-null    object
 12  Loan_Status        614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB

In [11]:
df.nunique()

Loan_ID              614
Gender                 2
Married                2
Dependents             4
Education              2
Self_Employed          2
ApplicantIncome      505
CoapplicantIncome    287
LoanAmount           203
Loan_Amount_Term      10
Credit_History         2
Property_Area          3
Loan_Status            2
dtype: int64

In [12]:
df.isna().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [13]:
df['CoapplicantIncome'].unique()

array([0.00000000e+00, 1.50800000e+03, 2.35800000e+03, 4.19600000e+03,
       1.51600000e+03, 2.50400000e+03, 1.52600000e+03, 1.09680000e+04,
       7.00000000e+02, 1.84000000e+03, 8.10600000e+03, 2.84000000e+03,
       1.08600000e+03, 3.50000000e+03, 5.62500000e+03, 1.91100000e+03,
       1.91700000e+03, 2.92500000e+03, 2.25300000e+03, 1.04000000e+03,
       2.08300000e+03, 3.36900000e+03, 1.66700000e+03, 3.00000000e+03,
       2.06700000e+03, 1.33000000e+03, 1.45900000e+03, 7.21000000e+03,
       1.66800000e+03, 1.21300000e+03, 2.33600000e+03, 3.44000000e+03,
       2.27500000e+03, 1.64400000e+03, 1.16700000e+03, 1.59100000e+03,
       2.20000000e+03, 2.25000000e+03, 2.85900000e+03, 3.79600000e+03,
       3.44900000e+03, 4.59500000e+03, 2.25400000e+03, 3.06600000e+03,
       1.87500000e+03, 1.77400000e+03, 4.75000000e+03, 3.02200000e+03,
       4.00000000e+03, 2.16600000e+03, 1.88100000e+03, 2.53100000e+03,
       2.00000000e+03, 2.11800000e+03, 4.16700000e+03, 2.90000000e+03,
       5.65400000e+03, 1.82000000e+03, 2.30200000e+03, 9.97000000e+02,
       3.54100000e+03, 3.26300000e+03, 3.80600000e+03, 3.58300000e+03,
       7.54000000e+02, 1.03000000e+03, 1.12600000e+03, 3.60000000e+03,
       2.33300000e+03, 4.11400000e+03, 2.28300000e+03, 1.39800000e+03,
       2.14200000e+03, 2.66700000e+03, 8.98000000e+03, 2.01400000e+03,
       1.64000000e+03, 3.85000000e+03, 2.56900000e+03, 1.92900000e+03,
       7.75000000e+03, 1.43000000e+03, 2.03400000e+03, 4.48600000e+03,
       1.42500000e+03, 1.66600000e+03, 8.30000000e+02, 3.75000000e+03,
       1.04100000e+03, 1.28000000e+03, 1.44700000e+03, 3.16600000e+03,
       3.33300000e+03, 1.76900000e+03, 7.36000000e+02, 1.96400000e+03,
       1.61900000e+03, 1.13000000e+04, 1.45100000e+03, 7.25000000e+03,
       5.06300000e+03, 2.13800000e+03, 5.29600000e+03, 2.58300000e+03,
       2.36500000e+03, 2.81600000e+03, 2.50000000e+03, 1.08300000e+03,
       1.25000000e+03, 3.02100000e+03, 9.83000000e+02, 1.80000000e+03,
       1.77500000e+03, 2.38300000e+03, 1.71700000e+03, 2.79100000e+03,
       1.01000000e+03, 1.69500000e+03, 2.05400000e+03, 2.59800000e+03,
       1.77900000e+03, 1.26000000e+03, 5.00000000e+03, 1.98300000e+03,
       5.70100000e+03, 1.30000000e+03, 4.41700000e+03, 4.33300000e+03,
       1.84300000e+03, 1.86800000e+03, 3.89000000e+03, 2.16700000e+03,
       7.10100000e+03, 2.10000000e+03, 4.25000000e+03, 2.20900000e+03,
       3.44700000e+03, 1.38700000e+03, 1.81100000e+03, 1.56000000e+03,
       1.85700000e+03, 2.22300000e+03, 1.84200000e+03, 3.27400000e+03,
       2.42600000e+03, 8.00000000e+02, 9.85799988e+02, 3.05300000e+03,
       2.41600000e+03, 3.33400000e+03, 2.54100000e+03, 2.93400000e+03,
       1.75000000e+03, 1.80300000e+03, 1.86300000e+03, 2.40500000e+03,
       2.13400000e+03, 1.89000000e+02, 1.59000000e+03, 2.98500000e+03,
       4.98300000e+03, 2.16000000e+03, 2.45100000e+03, 1.79300000e+03,
       1.83300000e+03, 4.49000000e+03, 6.88000000e+02, 4.60000000e+03,
       1.58700000e+03, 1.22900000e+03, 2.33000000e+03, 2.45800000e+03,
       3.23000000e+03, 2.16800000e+03, 4.58300000e+03, 6.25000000e+03,
       5.05000000e+02, 3.16700000e+03, 3.66700000e+03, 3.03300000e+03,
       5.26600000e+03, 7.87300000e+03, 1.98700000e+03, 9.23000000e+02,
       4.99600000e+03, 4.23200000e+03, 1.60000000e+03, 3.13600000e+03,
       2.41700000e+03, 2.11500000e+03, 1.62500000e+03, 1.40000000e+03,
       4.84000000e+02, 2.00000000e+04, 2.40000000e+03, 2.03300000e+03,
       3.23700000e+03, 2.77300000e+03, 1.41700000e+03, 1.71900000e+03,
       4.30000000e+03, 1.61200008e+01, 2.34000000e+03, 1.85100000e+03,
       1.12500000e+03, 5.06400000e+03, 1.99300000e+03, 8.33300000e+03,
       1.21000000e+03, 1.37600000e+03, 1.71000000e+03, 1.54200000e+03,
       1.25500000e+03, 1.45600000e+03, 1.73300000e+03, 2.46600000e+03,
       4.08300000e+03, 2.18800000e+03, 1.66400000e+03, 2.91700000e+03,
       2.07900000e+03, 1.50000000e+03, 4.64800000e+03, 1.01400000e+03,
       1.87200000e+03, 1.60300000e+03, 3.15000000e+03, 2.43600000e+03,
       2.78500000e+03, 1.13100000e+03, 2.15700000e+03, 9.13000000e+02,
       1.70000000e+03, 2.85700000e+03, 4.41600000e+03, 3.68300000e+03,
       5.62400000e+03, 5.30200000e+03, 1.48300000e+03, 6.66700000e+03,
       3.01300000e+03, 1.28700000e+03, 2.00400000e+03, 2.03500000e+03,
       6.66600000e+03, 3.66600000e+03, 3.42800000e+03, 1.63200000e+03,
       1.91500000e+03, 1.74200000e+03, 1.42400000e+03, 7.16600000e+03,
       2.08700000e+03, 1.30200000e+03, 5.50000000e+03, 2.04200000e+03,
       3.90600000e+03, 5.36000000e+02, 2.84500000e+03, 2.52400000e+03,
       6.63000000e+02, 1.95000000e+03, 1.78300000e+03, 2.01600000e+03,
       2.37500000e+03, 3.25000000e+03, 4.26600000e+03, 1.03200000e+03,
       2.66900000e+03, 2.30600000e+03, 2.42000000e+02, 2.06400000e+03,
       4.61000000e+02, 2.21000000e+03, 2.73900000e+03, 2.23200000e+03,
       3.38370000e+04, 1.52200000e+03, 3.41600000e+03, 3.30000000e+03,
       1.00000000e+03, 4.16670000e+04, 2.79200000e+03, 4.30100000e+03,
       3.80000000e+03, 1.41100000e+03, 2.40000000e+02])

In [14]:
df['ApplicantIncome'].unique()

array([ 5849,  4583,  3000,  2583,  6000,  5417,  2333,  3036,  4006,
       12841,  3200,  2500,  3073,  1853,  1299,  4950,  3596,  3510,
        4887,  2600,  7660,  5955,  3365,  3717,  9560,  2799,  4226,
        1442,  3750,  4166,  3167,  4692,  3500, 12500,  2275,  1828,
        3667,  3748,  3600,  1800,  2400,  3941,  4695,  3410,  5649,
        5821,  2645,  4000,  1928,  3086,  4230,  4616, 11500,  2708,
        2132,  3366,  8080,  3357,  3029,  2609,  4945,  5726, 10750,
        7100,  4300,  3208,  1875,  4755,  5266,  1000,  3333,  3846,
        2395,  1378,  3988,  2366,  8566,  5695,  2958,  6250,  3273,
        4133,  3620,  6782,  2484,  1977,  4188,  1759,  4288,  4843,
       13650,  4652,  3816,  3052, 11417,  7333,  3800,  2071,  5316,
        2929,  3572,  7451,  5050, 14583,  2214,  5568, 10408,  5667,
        2137,  2957,  3692, 23803,  3865, 10513,  6080, 20166,  2014,
        2718,  3459,  4895,  3316, 14999,  4200,  5042,  6950,  2698,
       11757,  2330, 14866,  1538, 10000,  4860,  6277,  2577,  9166,
        2281,  3254, 39999,  9538,  2980,  1863,  7933,  3089,  4167,
        9323,  3707,  2439,  2237,  8000,  1820, 51763,  3522,  5708,
        4344,  3497,  2045,  5516,  6400,  1916,  4600, 33846,  3625,
       39147,  2178,  2383,   674,  9328,  4885, 12000,  6033,  3858,
        4191,  3125,  8333,  1907,  3416, 11000,  4923,  3992,  3917,
        4408,  3244,  3975,  2479,  3418,  3430,  7787,  5703,  3173,
        3850,   150,  3727,  5000,  4283,  2221,  4009,  2971,  7578,
        3250,  4735,  4758,  2491,  3716,  3189,  3155,  5500,  5746,
        3463,  3812,  3315,  5819,  2510,  2965,  3406,  6050,  9703,
        6608,  2882,  1809,  1668,  3427,  2661, 16250,  3083,  6045,
        5250, 14683,  4931,  6083,  2060,  3481,  7200,  5166,  4095,
        4708,  4333,  2876,  3237, 11146,  2833,  2620,  3900,  2750,
        3993,  3103,  4100,  4053,  3927,  2301,  1811, 20667,  3158,
        3704,  4124,  9508,  3075,  4400,  3153,  4416,  6875,  4666,
        2875,  1625,  2000,  3762, 20233,  7667,  2917,  2927,  2507,
        2473,  3399,  2058,  3541,  4342,  3601,  3166, 15000,  8666,
        4917,  5818,  4384,  2935, 63337,  9833,  5503,  1830,  4160,
        2647,  2378,  4554,  2499,  3523,  6333,  2625,  9083,  8750,
        2666,  2423,  3813,  3875,  5167,  4723,  4750,  3013,  6822,
        6216,  5124,  6325, 19730, 15759,  5185,  3062,  2764,  4817,
        4310,  3069,  5391,  5941,  7167,  4566,  2346,  3010,  5488,
        9167,  9504,  1993,  3100,  3276,  3180,  3033,  3902,  1500,
        2889,  2755,  1963,  7441,  4547,  2167,  2213,  8300, 81000,
        3867,  6256,  6096,  2253,  2149,  2995,  1600,  1025,  3246,
        5829,  2720,  7250, 14880,  4606,  5935,  2920,  2717,  8624,
        6500, 12876,  2425, 10047,  1926, 10416,  7142,  3660,  7901,
        4707, 37719,  3466,  3539,  3340,  2769,  2309,  1958,  3948,
        2483,  7085,  3859,  4301,  3708,  4354,  8334,  2083,  7740,
        3015,  5191,  2947, 16692,   210,  3450,  2653,  4691,  5532,
       16525,  6700,  2873, 16667,  4350,  3095, 10833,  3547, 18333,
        2435,  2699,  5333,  3691, 17263,  3597,  3326,  4625,  2895,
        6283,   645,  3159,  4865,  4050,  3814, 20833,  3583, 13262,
        3598,  6065,  3283,  2130,  5815,  2031,  3074,  4683,  3400,
        2192,  5677,  7948,  4680, 17500,  3775,  5285,  2679,  6783,
        4281,  3588, 11250, 18165,  2550,  6133,  3617,  6417,  4608,
        2138,  3652,  2239,  3017,  2768,  3358,  2526,  2785,  6633,
        2492,  2454,  3593,  5468,  2667, 10139,  3887,  4180,  3675,
       19484,  5923,  5800,  8799,  4467,  3417,  5116, 16666,  6125,
        6406,  3087,  3229,  1782,  3182,  6540,  1836,  1880,  2787,
        2297,  2165,  2726,  9357, 16120,  3833,  6383,  2987,  9963,
        5780,   416,  2894,  3676,  3987,  3232,  2900,  4106,  8072,
        7583])

In [15]:
df.isna().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [16]:
import matplotlib.pyplot as plot

In [17]:
df.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [22]:
categorical_col = ['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed', 'Property_Area']
numerical_col = ['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount', 'Loan_Amount_Term']

In [21]:
data_encoded = pd.get_dummies(df,columns=categorical_col,dtype=int,drop_first=True)
data_encoded.head()

,Loan_ID,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Loan_Status,Gender_Male,Married_Yes,Dependents_1,Dependents_2,Dependents_3+,Education_Not Graduate,Self_Employed_Yes,Property_Area_Semiurban,Property_Area_Urban
0,LP001002,5849,0.0,128.0,360.0,1.0,Y,1,0,0,0,0,0,0,0,1
1,LP001003,4583,1508.0,128.0,360.0,1.0,N,1,1,1,0,0,0,0,0,0
2,LP001005,3000,0.0,66.0,360.0,1.0,Y,1,1,0,0,0,0,1,0,1
3,LP001006,2583,2358.0,120.0,360.0,1.0,Y,1,1,0,0,0,1,0,0,1
4,LP001008,6000,0.0,141.0,360.0,1.0,Y,1,0,0,0,0,0,0,0,1

,Loan_ID,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Loan_Status,Gender_Male,Married_Yes,Dependents_1,Dependents_2,Dependents_3+,Education_Not Graduate,Self_Employed_Yes,Property_Area_Semiurban,Property_Area_Urban
0,LP001002,5849,0.0,128.0,360.0,1.0,Y,1,0,0,0,0,0,0,0,1
1,LP001003,4583,1508.0,128.0,360.0,1.0,N,1,1,1,0,0,0,0,0,0
2,LP001005,3000,0.0,66.0,360.0,1.0,Y,1,1,0,0,0,0,1,0,1
3,LP001006,2583,2358.0,120.0,360.0,1.0,Y,1,1,0,0,0,1,0,0,1
4,LP001008,6000,0.0,141.0,360.0,1.0,Y,1,0,0,0,0,0,0,0,1

In [23]:
data_encoded.shape

(614, 16)

In [25]:
data_encoded.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Loan_ID                  614 non-null    object
 1   ApplicantIncome          614 non-null    int64
 2   CoapplicantIncome        614 non-null    float64
 3   LoanAmount               614 non-null    float64
 4   Loan_Amount_Term         614 non-null    float64
 5   Credit_History           614 non-null    float64
 6   Loan_Status              614 non-null    object
 7   Gender_Male              614 non-null    int64
 8   Married_Yes              614 non-null    int64
 9   Dependents_1             614 non-null    int64
 10  Dependents_2             614 non-null    int64
 11  Dependents_3+            614 non-null    int64
 12  Education_Not Graduate   614 non-null    int64
 13  Self_Employed_Yes        614 non-null    int64
 14  Property_Area_Semiurban  614 non-null    int64
 15  Property_Area_Urban      614 non-null    int64
dtypes: float64(4), int64(10), object(2)
memory usage: 76.9+ KB

In [27]:
data_std_scaled =data_encoded.copy()

std_scaler = StandardScaler()
data_std_scaled[numerical_col] = std_scaler.fit_transform(data_std_scaled[numerical_col])
data_std_scaled.head()

,Loan_ID,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Loan_Status,Gender_Male,Married_Yes,Dependents_1,Dependents_2,Dependents_3+,Education_Not Graduate,Self_Employed_Yes,Property_Area_Semiurban,Property_Area_Urban
0,LP001002,0.072991,-0.554487,-0.221466,0.280037,1.0,Y,1,0,0,0,0,0,0,0,1
1,LP001003,-0.134412,-0.038732,-0.221466,0.280037,1.0,N,1,1,1,0,0,0,0,0,0
2,LP001005,-0.393747,-0.554487,-0.931066,0.280037,1.0,Y,1,1,0,0,0,0,1,0,1
3,LP001006,-0.462062,0.251980,-0.313027,0.280037,1.0,Y,1,1,0,0,0,1,0,0,1
4,LP001008,0.097728,-0.554487,-0.072679,0.280037,1.0,Y,1,0,0,0,0,0,0,0,1

In [28]:
data_minmax_scaled =data_encoded.copy()

minmax_scaler = MinMaxScaler()
data_minmax_scaled[numerical_col] = std_scaler.fit_transform(data_minmax_scaled[numerical_col])
data_minmax_scaled.head()

,Loan_ID,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Loan_Status,Gender_Male,Married_Yes,Dependents_1,Dependents_2,Dependents_3+,Education_Not Graduate,Self_Employed_Yes,Property_Area_Semiurban,Property_Area_Urban
0,LP001002,0.072991,-0.554487,-0.221466,0.280037,1.0,Y,1,0,0,0,0,0,0,0,1
1,LP001003,-0.134412,-0.038732,-0.221466,0.280037,1.0,N,1,1,1,0,0,0,0,0,0
2,LP001005,-0.393747,-0.554487,-0.931066,0.280037,1.0,Y,1,1,0,0,0,0,1,0,1
3,LP001006,-0.462062,0.251980,-0.313027,0.280037,1.0,Y,1,1,0,0,0,1,0,0,1
4,LP001008,0.097728,-0.554487,-0.072679,0.280037,1.0,Y,1,0,0,0,0,0,0,0,1

In [30]:
data_encoded.columns

Index(['Loan_ID', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Loan_Status', 'Gender_Male',
       'Married_Yes', 'Dependents_1', 'Dependents_2', 'Dependents_3+',
       'Education_Not Graduate', 'Self_Employed_Yes',
       'Property_Area_Semiurban', 'Property_Area_Urban'],
      dtype='object')

In [31]:
corr_columns =['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount', 'Loan_Amount_Term']
original_data_corr =data_encoded[corr_columns].corr()
original_data_corr

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term
ApplicantIncome,1.000000,-0.116605,0.533336,-0.042849
CoapplicantIncome,-0.116605,1.000000,0.189820,-0.067336
LoanAmount,0.533336,0.189820,1.000000,0.023657
Loan_Amount_Term,-0.042849,-0.067336,0.023657,1.000000

In [32]:
scaled_data_corr =data_std_scaled[corr_columns].corr()
scaled_data_corr

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term
ApplicantIncome,1.000000,-0.116605,0.533336,-0.042849
CoapplicantIncome,-0.116605,1.000000,0.189820,-0.067336
LoanAmount,0.533336,0.189820,1.000000,0.023657
Loan_Amount_Term,-0.042849,-0.067336,0.023657,1.000000

In [34]:
Q1 =np.percentile(df['LoanAmount'],25,interpolation='midpoint')
Q2 =np.percentile(df['LoanAmount'],50,interpolation='midpoint')
Q3 =np.percentile(df['LoanAmount'],75,interpolation='midpoint')

In [35]:
print(Q1)
print(Q2)
print(Q3)

100.0
128.0
167.5

In [36]:
IQR=Q3-Q1
print(IQR)

67.5

In [37]:
min_val=Q1-1.5*IQR
max_val=Q3+1.5*IQR
print(min_val,max_val)

-1.25 268.75